/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILineaBridge,
  ILineaBridgeInterface,
} from "../../../contracts/ConversionAdapter.sol/ILineaBridge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILineaBridge__factory {
  static readonly abi = _abi;
  static createInterface(): ILineaBridgeInterface {
    return new Interface(_abi) as ILineaBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILineaBridge {
    return new Contract(address, _abi, runner) as unknown as ILineaBridge;
  }
}
