/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConversionAdapter } from "./ConversionAdapter";
export type { ILineaBridge } from "./ILineaBridge";
