/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILineaSwapAdapter,
  ILineaSwapAdapterInterface,
} from "../../../contracts/HoneyPotPot.sol/ILineaSwapAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "swap",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILineaSwapAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): ILineaSwapAdapterInterface {
    return new Interface(_abi) as ILineaSwapAdapterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILineaSwapAdapter {
    return new Contract(address, _abi, runner) as unknown as ILineaSwapAdapter;
  }
}
