/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from "./MockERC20";
export type { VRFCoordinatorV2Mock } from "./VRFCoordinatorV2Mock";
